version: "3.7"

services:
  app:
    build: 
      context: .
    image: liz/bot
    restart: on-failure
    environment:
      TZ: ${TIMEZONE}
      BOT_NAME: ${BOT_NAME}
      PGHOST: postgres
      PGDATABASE: ${DB_NAME}
      PGPASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_USER}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PREFIX: ${PREFIX}
      DEFAULT_LANG: ${DEFAULT_LANG}
      SUPPORTED_LANG: ${SUPPORTED_LANG}
      LANG_DIR: ${LANG_DIR}
      OWNER_ID: ${OWNER_ID}
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - ./dbVolume:/docker-entrypoint-initdb.d
      - botData:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  botData: